name: pokeapi_dart
description: All the Pokémon data you'll ever need in one place, easily accessible through a modern RESTful API.
version: 0.0.1-dev.1
homepage: https://chulwoo.dev
repository: https://github.com/chulwoo-park/pokeapi_dart/
issue_tracker: https://github.com/chulwoo-park/pokeapi_dart/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.2.4
  freezed_annotation: ^0.12.0
  http: ^0.12.2

dev_dependencies:
  build_runner: 1.10.2
  # hangs on latest analyzer, freezed
  analyzer: ^0.39.17
  freezed: ^0.12.2
  # build_runner: ^1.10.6
  json_serializable: ^3.5.0
  test: ^1.15.7
  test_coverage: ^0.5.0
  remove_from_coverage: ^1.0.7
  