name: Codecov
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest

    steps:
      - uses: actions/checkout@v1
      - name: Checkout api data submodule
        uses: actions/checkout@v2.0.0
        with:
          repository: PokeAPI/api-data
          path: test/api-data
          ref: 'master'
      - name: Install dependencies
        run: pub get
      - name: Run tests
        run: pub run test
      - name: Code Coverage
        run: pub run test_coverage
      - name: Remove generated files from coverage
        run: pub run remove_from_coverage -f coverage/lcov.info -r '.g.dart$|.freezed.dart$'
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: coverage/lcov.info
